### ISSUE TITLE
你好，想请教一下字体转换

### ISSUE THREAD

**Issue by wuchenchina** [satouriko/LxgwWenKai_Webfonts#1]
您好！想来请教一下字体转换，可能是我比较笨，在看[技术](https://github.com/fontsource/fontsource)时一头雾水，望指明方向，有ttf文件，想转换成dist里面的内容，不清楚怎么搞，所以来请教一下

**Comment by satouriko** [comment]
[build.js](https://github.com/satouriko/LxgwWenKai_Webfonts/blob/master/build.js) 就是用来转换的代码

**Comment by ghost** [comment]
行，我看下，感谢！
